services:
  - type: web
    name: your-laravel-backend
    env: docker # Cấu hình Render để sử dụng Dockerfile
    rootDir: backend # Vẫn trỏ tới thư mục backend
    plan: free
    
    # Render sẽ tự động tìm Dockerfile và chạy build
    # buildCommand và startCommand sẽ không cần thiết nữa

    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: "production"
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: mysql # Hoặc postgres
      - key: DB_HOST
        fromDatabase:
          name: your-database-name
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: your-database-name
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: your-database-name
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: your-database-name
          property: password